type: "survival"

currencies:
  credits:
    display-name: "Kredity"

disabled-pvp:
  - "world_nether"
  - "world_the_end"
  - "MineWorld"

banned-words:
  - "kurva"
  - "kokot"
  - "pica"
  - "piča"
  - "píča"
  - "píčo"
  - "pico"
  - "píčus"
  - "pičus"
  - "debile"
  - "kokote"
  - "kokoti"
  - "kokotina"
  - "kokotiny"
  - "zmrd"
  - "zmrdi"

residence-command-blocker:
  EventLand:
    execute-commands: []
    allowed-commands:
      - '/spawn'
      - '/cmi spawn'
      - '/sethome'
      - '/home'
      - '/homes'
      - '/warp'
    blacklist-commands:
      - '*'

mineworld:
  spawn-location: "MineWorld;255;50;255;1;1"
  maximum: 5000
  blocks:
    GRASS_BLOCK:
      price: 1
  welcome-message:
    - '&r'
    - '&r'
    - '                       &e&nMineWorld'
    - '&r'
    - '&7Nyní získáváš peníze kopáním materiálů &cpouze &7v &e/mineworld&7.'
    - '  &71x Grass Block = &e${GRASS_BLOCK}'
    - '&r'
    - '&cAle pozor &4- &7za den můžeš vytěžit jen {maximum} bloků!'
    - '&r'

webhooks:
  maintenance: 'https://discord.com/api/webhooks/1166686239018209301/2OHIa8oSQ6FXFSg2rWr18nWz1jhnH0NKinYaAQooqhDl9MJCEzJmqziWcAeOD0r3UbPQ'