type: "survival"

currencies:
  credits:
    display-name: "Kredity"

disabled-pvp:
  - "world_nether"
  - "world_the_end"
  - "MineWorld"

banned-words:
  - "kurva"
  - "kokot"
  - "pica"
  - "piča"
  - "píča"
  - "píčo"
  - "pico"
  - "píčus"
  - "pičus"
  - "debile"
  - "kokote"
  - "kokoti"
  - "kokotina"
  - "kokotiny"
  - "zmrd"
  - "zmrdi"

residence-command-blocker:
  EventLand:
    execute-commands: []
    allowed-commands:
      - '/spawn'
      - '/cmi spawn'
      - '/sethome'
      - '/home'
      - '/homes'
      - '/warp'
    blacklist-commands:
      - '*'